services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    user: root
    environment:
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT:-80}
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_LISTEN_PORT:-5050}:${PGADMIN_LISTEN_PORT:-80}"
    restart: unless-stopped
#
#  postgres:
#    container_name: postgres
#    image: postgres
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-postgres}
#      POSTGRES_USER: ${POSTGRES_USER:-pg_user_name}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg_password}
#      PGDATA: ${POSTGRES_DATA:-/var/lib/postgresql/data/pgdata}
#    volumes:
#      - ./postgres:${POSTGRES_DATA:-/var/lib/postgresql/data/pgdata}
#    ports:
#      - "${POSTGRES_PORT}:5432"
#    restart: unless-stopped

volumes:
  pgadmin:

